export const COUNTRIES = [
  // France first (default)
  { code: 'FR', flag: '🇫🇷', name: 'France', nameEn: 'France', dialCode: '+33' },
  // Rest alphabetically by English name
  { code: 'AF', flag: '🇦🇫', name: 'Afghanistan', nameEn: 'Afghanistan', dialCode: '+93' },
  { code: 'AL', flag: '🇦🇱', name: 'Albanie', nameEn: 'Albania', dialCode: '+355' },
  { code: 'DZ', flag: '🇩🇿', name: 'Algérie', nameEn: 'Algeria', dialCode: '+213' },
  { code: 'AD', flag: '🇦🇩', name: 'Andorre', nameEn: 'Andorra', dialCode: '+376' },
  { code: 'AO', flag: '🇦🇴', name: 'Angola', nameEn: 'Angola', dialCode: '+244' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentine', nameEn: 'Argentina', dialCode: '+54' },
  { code: 'AM', flag: '🇦🇲', name: 'Arménie', nameEn: 'Armenia', dialCode: '+374' },
  { code: 'AU', flag: '🇦🇺', name: 'Australie', nameEn: 'Australia', dialCode: '+61' },
  { code: 'AT', flag: '🇦🇹', name: 'Autriche', nameEn: 'Austria', dialCode: '+43' },
  { code: 'AZ', flag: '🇦🇿', name: 'Azerbaïdjan', nameEn: 'Azerbaijan', dialCode: '+994' },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh', nameEn: 'Bangladesh', dialCode: '+880' },
  { code: 'BY', flag: '🇧🇾', name: 'Biélorussie', nameEn: 'Belarus', dialCode: '+375' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgique', nameEn: 'Belgium', dialCode: '+32' },
  { code: 'BO', flag: '🇧🇴', name: 'Bolivie', nameEn: 'Bolivia', dialCode: '+591' },
  { code: 'BA', flag: '🇧🇦', name: 'Bosnie-Herzégovine', nameEn: 'Bosnia and Herzegovina', dialCode: '+387' },
  { code: 'BR', flag: '🇧🇷', name: 'Brésil', nameEn: 'Brazil', dialCode: '+55' },
  { code: 'BF', flag: '🇧🇫', name: 'Burkina Faso', nameEn: 'Burkina Faso', dialCode: '+226' },
  { code: 'KH', flag: '🇰🇭', name: 'Cambodge', nameEn: 'Cambodia', dialCode: '+855' },
  { code: 'CM', flag: '🇨🇲', name: 'Cameroun', nameEn: 'Cameroon', dialCode: '+237' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada', nameEn: 'Canada', dialCode: '+1' },
  { code: 'CL', flag: '🇨🇱', name: 'Chili', nameEn: 'Chile', dialCode: '+56' },
  { code: 'CN', flag: '🇨🇳', name: 'Chine', nameEn: 'China', dialCode: '+86' },
  { code: 'CY', flag: '🇨🇾', name: 'Chypre', nameEn: 'Cyprus', dialCode: '+357' },
  { code: 'CO', flag: '🇨🇴', name: 'Colombie', nameEn: 'Colombia', dialCode: '+57' },
  { code: 'CD', flag: '🇨🇩', name: 'Congo (RDC)', nameEn: 'Congo (DR)', dialCode: '+243' },
  { code: 'CG', flag: '🇨🇬', name: 'Congo (Rép.)', nameEn: 'Congo (Rep.)', dialCode: '+242' },
  { code: 'CR', flag: '🇨🇷', name: 'Costa Rica', nameEn: 'Costa Rica', dialCode: '+506' },
  { code: 'CI', flag: '🇨🇮', name: "Côte d'Ivoire", nameEn: "Ivory Coast", dialCode: '+225' },
  { code: 'HR', flag: '🇭🇷', name: 'Croatie', nameEn: 'Croatia', dialCode: '+385' },
  { code: 'CU', flag: '🇨🇺', name: 'Cuba', nameEn: 'Cuba', dialCode: '+53' },
  { code: 'CZ', flag: '🇨🇿', name: 'Tchéquie', nameEn: 'Czech Republic', dialCode: '+420' },
  { code: 'DK', flag: '🇩🇰', name: 'Danemark', nameEn: 'Denmark', dialCode: '+45' },
  { code: 'DO', flag: '🇩🇴', name: 'Rép. Dominicaine', nameEn: 'Dominican Republic', dialCode: '+1809' },
  { code: 'EC', flag: '🇪🇨', name: 'Équateur', nameEn: 'Ecuador', dialCode: '+593' },
  { code: 'EG', flag: '🇪🇬', name: 'Égypte', nameEn: 'Egypt', dialCode: '+20' },
  { code: 'SV', flag: '🇸🇻', name: 'El Salvador', nameEn: 'El Salvador', dialCode: '+503' },
  { code: 'EE', flag: '🇪🇪', name: 'Estonie', nameEn: 'Estonia', dialCode: '+372' },
  { code: 'ET', flag: '🇪🇹', name: 'Éthiopie', nameEn: 'Ethiopia', dialCode: '+251' },
  { code: 'FI', flag: '🇫🇮', name: 'Finlande', nameEn: 'Finland', dialCode: '+358' },
  { code: 'GA', flag: '🇬🇦', name: 'Gabon', nameEn: 'Gabon', dialCode: '+241' },
  { code: 'GE', flag: '🇬🇪', name: 'Géorgie', nameEn: 'Georgia', dialCode: '+995' },
  { code: 'DE', flag: '🇩🇪', name: 'Allemagne', nameEn: 'Germany', dialCode: '+49' },
  { code: 'GH', flag: '🇬🇭', name: 'Ghana', nameEn: 'Ghana', dialCode: '+233' },
  { code: 'GR', flag: '🇬🇷', name: 'Grèce', nameEn: 'Greece', dialCode: '+30' },
  { code: 'GT', flag: '🇬🇹', name: 'Guatemala', nameEn: 'Guatemala', dialCode: '+502' },
  { code: 'GN', flag: '🇬🇳', name: 'Guinée', nameEn: 'Guinea', dialCode: '+224' },
  { code: 'HN', flag: '🇭🇳', name: 'Honduras', nameEn: 'Honduras', dialCode: '+504' },
  { code: 'HK', flag: '🇭🇰', name: 'Hong Kong', nameEn: 'Hong Kong', dialCode: '+852' },
  { code: 'HU', flag: '🇭🇺', name: 'Hongrie', nameEn: 'Hungary', dialCode: '+36' },
  { code: 'IS', flag: '🇮🇸', name: 'Islande', nameEn: 'Iceland', dialCode: '+354' },
  { code: 'IN', flag: '🇮🇳', name: 'Inde', nameEn: 'India', dialCode: '+91' },
  { code: 'ID', flag: '🇮🇩', name: 'Indonésie', nameEn: 'Indonesia', dialCode: '+62' },
  { code: 'IR', flag: '🇮🇷', name: 'Iran', nameEn: 'Iran', dialCode: '+98' },
  { code: 'IQ', flag: '🇮🇶', name: 'Irak', nameEn: 'Iraq', dialCode: '+964' },
  { code: 'IE', flag: '🇮🇪', name: 'Irlande', nameEn: 'Ireland', dialCode: '+353' },
  { code: 'IL', flag: '🇮🇱', name: 'Israël', nameEn: 'Israel', dialCode: '+972' },
  { code: 'IT', flag: '🇮🇹', name: 'Italie', nameEn: 'Italy', dialCode: '+39' },
  { code: 'JP', flag: '🇯🇵', name: 'Japon', nameEn: 'Japan', dialCode: '+81' },
  { code: 'JO', flag: '🇯🇴', name: 'Jordanie', nameEn: 'Jordan', dialCode: '+962' },
  { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan', nameEn: 'Kazakhstan', dialCode: '+7' },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya', nameEn: 'Kenya', dialCode: '+254' },
  { code: 'KW', flag: '🇰🇼', name: 'Koweït', nameEn: 'Kuwait', dialCode: '+965' },
  { code: 'LA', flag: '🇱🇦', name: 'Laos', nameEn: 'Laos', dialCode: '+856' },
  { code: 'LV', flag: '🇱🇻', name: 'Lettonie', nameEn: 'Latvia', dialCode: '+371' },
  { code: 'LB', flag: '🇱🇧', name: 'Liban', nameEn: 'Lebanon', dialCode: '+961' },
  { code: 'LY', flag: '🇱🇾', name: 'Libye', nameEn: 'Libya', dialCode: '+218' },
  { code: 'LI', flag: '🇱🇮', name: 'Liechtenstein', nameEn: 'Liechtenstein', dialCode: '+423' },
  { code: 'LT', flag: '🇱🇹', name: 'Lituanie', nameEn: 'Lithuania', dialCode: '+370' },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg', nameEn: 'Luxembourg', dialCode: '+352' },
  { code: 'MG', flag: '🇲🇬', name: 'Madagascar', nameEn: 'Madagascar', dialCode: '+261' },
  { code: 'MY', flag: '🇲🇾', name: 'Malaisie', nameEn: 'Malaysia', dialCode: '+60' },
  { code: 'ML', flag: '🇲🇱', name: 'Mali', nameEn: 'Mali', dialCode: '+223' },
  { code: 'MT', flag: '🇲🇹', name: 'Malte', nameEn: 'Malta', dialCode: '+356' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexique', nameEn: 'Mexico', dialCode: '+52' },
  { code: 'MD', flag: '🇲🇩', name: 'Moldavie', nameEn: 'Moldova', dialCode: '+373' },
  { code: 'MC', flag: '🇲🇨', name: 'Monaco', nameEn: 'Monaco', dialCode: '+377' },
  { code: 'MN', flag: '🇲🇳', name: 'Mongolie', nameEn: 'Mongolia', dialCode: '+976' },
  { code: 'ME', flag: '🇲🇪', name: 'Monténégro', nameEn: 'Montenegro', dialCode: '+382' },
  { code: 'MA', flag: '🇲🇦', name: 'Maroc', nameEn: 'Morocco', dialCode: '+212' },
  { code: 'MZ', flag: '🇲🇿', name: 'Mozambique', nameEn: 'Mozambique', dialCode: '+258' },
  { code: 'MM', flag: '🇲🇲', name: 'Myanmar', nameEn: 'Myanmar', dialCode: '+95' },
  { code: 'NL', flag: '🇳🇱', name: 'Pays-Bas', nameEn: 'Netherlands', dialCode: '+31' },
  { code: 'NZ', flag: '🇳🇿', name: 'Nouvelle-Zélande', nameEn: 'New Zealand', dialCode: '+64' },
  { code: 'NI', flag: '🇳🇮', name: 'Nicaragua', nameEn: 'Nicaragua', dialCode: '+505' },
  { code: 'NE', flag: '🇳🇪', name: 'Niger', nameEn: 'Niger', dialCode: '+227' },
  { code: 'NG', flag: '🇳🇬', name: 'Nigéria', nameEn: 'Nigeria', dialCode: '+234' },
  { code: 'MK', flag: '🇲🇰', name: 'Macédoine du Nord', nameEn: 'North Macedonia', dialCode: '+389' },
  { code: 'NO', flag: '🇳🇴', name: 'Norvège', nameEn: 'Norway', dialCode: '+47' },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan', nameEn: 'Pakistan', dialCode: '+92' },
  { code: 'PA', flag: '🇵🇦', name: 'Panama', nameEn: 'Panama', dialCode: '+507' },
  { code: 'PY', flag: '🇵🇾', name: 'Paraguay', nameEn: 'Paraguay', dialCode: '+595' },
  { code: 'PE', flag: '🇵🇪', name: 'Pérou', nameEn: 'Peru', dialCode: '+51' },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines', nameEn: 'Philippines', dialCode: '+63' },
  { code: 'PL', flag: '🇵🇱', name: 'Pologne', nameEn: 'Poland', dialCode: '+48' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal', nameEn: 'Portugal', dialCode: '+351' },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar', nameEn: 'Qatar', dialCode: '+974' },
  { code: 'RO', flag: '🇷🇴', name: 'Roumanie', nameEn: 'Romania', dialCode: '+40' },
  { code: 'RU', flag: '🇷🇺', name: 'Russie', nameEn: 'Russia', dialCode: '+7' },
  { code: 'RW', flag: '🇷🇼', name: 'Rwanda', nameEn: 'Rwanda', dialCode: '+250' },
  { code: 'SA', flag: '🇸🇦', name: 'Arabie Saoudite', nameEn: 'Saudi Arabia', dialCode: '+966' },
  { code: 'SN', flag: '🇸🇳', name: 'Sénégal', nameEn: 'Senegal', dialCode: '+221' },
  { code: 'RS', flag: '🇷🇸', name: 'Serbie', nameEn: 'Serbia', dialCode: '+381' },
  { code: 'SG', flag: '🇸🇬', name: 'Singapour', nameEn: 'Singapore', dialCode: '+65' },
  { code: 'SK', flag: '🇸🇰', name: 'Slovaquie', nameEn: 'Slovakia', dialCode: '+421' },
  { code: 'SI', flag: '🇸🇮', name: 'Slovénie', nameEn: 'Slovenia', dialCode: '+386' },
  { code: 'ZA', flag: '🇿🇦', name: 'Afrique du Sud', nameEn: 'South Africa', dialCode: '+27' },
  { code: 'KR', flag: '🇰🇷', name: 'Corée du Sud', nameEn: 'South Korea', dialCode: '+82' },
  { code: 'ES', flag: '🇪🇸', name: 'Espagne', nameEn: 'Spain', dialCode: '+34' },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka', nameEn: 'Sri Lanka', dialCode: '+94' },
  { code: 'SE', flag: '🇸🇪', name: 'Suède', nameEn: 'Sweden', dialCode: '+46' },
  { code: 'CH', flag: '🇨🇭', name: 'Suisse', nameEn: 'Switzerland', dialCode: '+41' },
  { code: 'SY', flag: '🇸🇾', name: 'Syrie', nameEn: 'Syria', dialCode: '+963' },
  { code: 'TW', flag: '🇹🇼', name: 'Taïwan', nameEn: 'Taiwan', dialCode: '+886' },
  { code: 'TZ', flag: '🇹🇿', name: 'Tanzanie', nameEn: 'Tanzania', dialCode: '+255' },
  { code: 'TH', flag: '🇹🇭', name: 'Thaïlande', nameEn: 'Thailand', dialCode: '+66' },
  { code: 'TG', flag: '🇹🇬', name: 'Togo', nameEn: 'Togo', dialCode: '+228' },
  { code: 'TN', flag: '🇹🇳', name: 'Tunisie', nameEn: 'Tunisia', dialCode: '+216' },
  { code: 'TR', flag: '🇹🇷', name: 'Turquie', nameEn: 'Turkey', dialCode: '+90' },
  { code: 'UG', flag: '🇺🇬', name: 'Ouganda', nameEn: 'Uganda', dialCode: '+256' },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine', nameEn: 'Ukraine', dialCode: '+380' },
  { code: 'AE', flag: '🇦🇪', name: 'Émirats Arabes Unis', nameEn: 'United Arab Emirates', dialCode: '+971' },
  { code: 'GB', flag: '🇬🇧', name: 'Royaume-Uni', nameEn: 'United Kingdom', dialCode: '+44' },
  { code: 'US', flag: '🇺🇸', name: 'États-Unis', nameEn: 'United States', dialCode: '+1' },
  { code: 'UY', flag: '🇺🇾', name: 'Uruguay', nameEn: 'Uruguay', dialCode: '+598' },
  { code: 'UZ', flag: '🇺🇿', name: 'Ouzbékistan', nameEn: 'Uzbekistan', dialCode: '+998' },
  { code: 'VE', flag: '🇻🇪', name: 'Venezuela', nameEn: 'Venezuela', dialCode: '+58' },
  { code: 'VN', flag: '🇻🇳', name: 'Viêt Nam', nameEn: 'Vietnam', dialCode: '+84' },
  { code: 'ZW', flag: '🇿🇼', name: 'Zimbabwe', nameEn: 'Zimbabwe', dialCode: '+263' },
];

export function getCountryByCode(code) {
  return COUNTRIES.find((c) => c.code === code) || COUNTRIES[0];
}
