export const COUNTRIES = [
  { code: 'FR', flag: '🇫🇷', name: 'France', nameEn: 'France', dialCode: '+33' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgique', nameEn: 'Belgium', dialCode: '+32' },
  { code: 'CH', flag: '🇨🇭', name: 'Suisse', nameEn: 'Switzerland', dialCode: '+41' },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg', nameEn: 'Luxembourg', dialCode: '+352' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada', nameEn: 'Canada', dialCode: '+1' },
  { code: 'US', flag: '🇺🇸', name: 'États-Unis', nameEn: 'United States', dialCode: '+1' },
  { code: 'GB', flag: '🇬🇧', name: 'Royaume-Uni', nameEn: 'United Kingdom', dialCode: '+44' },
  { code: 'DE', flag: '🇩🇪', name: 'Allemagne', nameEn: 'Germany', dialCode: '+49' },
  { code: 'ES', flag: '🇪🇸', name: 'Espagne', nameEn: 'Spain', dialCode: '+34' },
  { code: 'IT', flag: '🇮🇹', name: 'Italie', nameEn: 'Italy', dialCode: '+39' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal', nameEn: 'Portugal', dialCode: '+351' },
  { code: 'NL', flag: '🇳🇱', name: 'Pays-Bas', nameEn: 'Netherlands', dialCode: '+31' },
  { code: 'PL', flag: '🇵🇱', name: 'Pologne', nameEn: 'Poland', dialCode: '+48' },
  { code: 'SE', flag: '🇸🇪', name: 'Suède', nameEn: 'Sweden', dialCode: '+46' },
  { code: 'NO', flag: '🇳🇴', name: 'Norvège', nameEn: 'Norway', dialCode: '+47' },
  { code: 'DK', flag: '🇩🇰', name: 'Danemark', nameEn: 'Denmark', dialCode: '+45' },
  { code: 'FI', flag: '🇫🇮', name: 'Finlande', nameEn: 'Finland', dialCode: '+358' },
  { code: 'RU', flag: '🇷🇺', name: 'Russie', nameEn: 'Russia', dialCode: '+7' },
  { code: 'TR', flag: '🇹🇷', name: 'Turquie', nameEn: 'Turkey', dialCode: '+90' },
  { code: 'MA', flag: '🇲🇦', name: 'Maroc', nameEn: 'Morocco', dialCode: '+212' },
  { code: 'DZ', flag: '🇩🇿', name: 'Algérie', nameEn: 'Algeria', dialCode: '+213' },
  { code: 'TN', flag: '🇹🇳', name: 'Tunisie', nameEn: 'Tunisia', dialCode: '+216' },
  { code: 'SN', flag: '🇸🇳', name: 'Sénégal', nameEn: 'Senegal', dialCode: '+221' },
  { code: 'CI', flag: '🇨🇮', name: "Côte d'Ivoire", nameEn: "Ivory Coast", dialCode: '+225' },
  { code: 'CM', flag: '🇨🇲', name: 'Cameroun', nameEn: 'Cameroon', dialCode: '+237' },
  { code: 'MG', flag: '🇲🇬', name: 'Madagascar', nameEn: 'Madagascar', dialCode: '+261' },
  { code: 'BR', flag: '🇧🇷', name: 'Brésil', nameEn: 'Brazil', dialCode: '+55' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentine', nameEn: 'Argentina', dialCode: '+54' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexique', nameEn: 'Mexico', dialCode: '+52' },
  { code: 'CN', flag: '🇨🇳', name: 'Chine', nameEn: 'China', dialCode: '+86' },
  { code: 'JP', flag: '🇯🇵', name: 'Japon', nameEn: 'Japan', dialCode: '+81' },
  { code: 'KR', flag: '🇰🇷', name: 'Corée du Sud', nameEn: 'South Korea', dialCode: '+82' },
  { code: 'IN', flag: '🇮🇳', name: 'Inde', nameEn: 'India', dialCode: '+91' },
  { code: 'AU', flag: '🇦🇺', name: 'Australie', nameEn: 'Australia', dialCode: '+61' },
  { code: 'ZA', flag: '🇿🇦', name: 'Afrique du Sud', nameEn: 'South Africa', dialCode: '+27' },
];

export function getCountryByCode(code) {
  return COUNTRIES.find((c) => c.code === code) || COUNTRIES[0];
}
